### ISSUE TITLE
Shall we propose this as a chef-rfc?

### ISSUE THREAD

**Issue by philoserf** [chef-community/cvp#1]
This looks like a good candidate for the Chef RFC process. I say I'm a little suprised that the 'community activity' was created in the chef repo when it could have been placed here.

References:
https://www.chef.io/community/
https://github.com/chef/chef-rfc

**Comment by miketheman** [comment]
@philoserf The CVP here predated the RFC repo and procedure by at least a year, if not more.

Considering this process applies to cookbook authorship, where might you suggest it be part of the Chef RFC process?

**Comment by philoserf** [comment]
@miketheman Indeed. That is what I was trying to say.
